### ISSUE TITLE
Update of Webdriver manager required to work with chrome 115+

### ISSUE THREAD

**Issue by Valeriy2013** [aquality-automation/aquality-selenium-core-dotnet#110]

**Comment by khramovv** [comment]
It is a blocker for us at the moment. Can it be updated?

**Comment by mialeska** [comment]
We will try to apply this update in the next week. Thank you for your patience!

**Comment by mialeska** [comment]
@khramovv @Valeriy2013  We have released Aquality.Selenium 4.12.2 with the latest Selenium and WebDriverManager versions, you could check it out as Nuget package. Thanks
